### ISSUE TITLE
ImageMagic convert burst the CPU / RAM

### ISSUE THREAD

**Issue by konrad79** [entorb/COVID-19-Coronavirus-German-Regions#4]
If I run the python script under Windows 10 with

`python3 gen-map-de-districts.py`

the convert.exe of ImageMagick runs the CPU near 100% for hours and the memory consumption of convert.exe exceeds 15GB.
Is this a bug of the python script or of ImageMagick (version 7.0.11)

Call for ImageMagick:

`['C:\\Program Files\\ImageMagick\\convert.exe', 'convert', 'maps/out/de-districts/Cases_Last_Week_Per_100000-*.gif', '-coalesce', '-fuzz', '2%', '+dither', '-layers', 'Optimize', 'maps/de-districts-Cases_Last_Week_Per_100000.gif']`

**Comment by entorb** [comment]
Sorry, I somehow missed you issue. 

I did not check the performance of this script in ages. Today it ran for almost 1h according to GitHub action. The reason is, that it renders 4 svg images per day, that are later converted to gifs per month and than gifs over all time. This is quite some work. A possible way for an improvement would be to keep the gifs per month and only recreate the images for the current month. But as I am quite busy I so far do not have plans to modify this logic. Feel free to propose a pull request. Best

**Comment by entorb** [comment]
now fixed, by keeping the generated gif of old months, so computing time is drastically reduced
